// c7#gbw11.tpa.tpa, created 2016-12-19 14:09:40 -0300 by /Users/nico/7c-galileo/gembow_gen.rb.
LPF ADD_ITEM_EFFECT
  INT_VAR
    type = 4
    opcode = 12
    duration = 6
    parameter1 = 1
    parameter2 = 1048576
    timing = 4
    target = 2
END

LPF ADD_ITEM_EFFECT
  INT_VAR
    type = 4
    opcode = 12
    duration = 12
    parameter1 = 1
    parameter2 = 1048576
    timing = 4
    target = 2
END