// c7#gbw08.tpa.tpa, created 2016-12-19 14:09:40 -0300 by /Users/nico/7c-galileo/gembow_gen.rb.
LPF ADD_ITEM_EFFECT
  INT_VAR
    opcode = 146
    type = 4
    target = 2
    resist_dispel = 1
    parameter2 = 1
    parameter1 = 1
  STR_VAR
    resource = "c7#gbw08"
END

INNER_ACTION BEGIN
  COPY_EXISTING spwi105.spl "override/c7#gbw08.spl"
    LPF DELETE_SPELL_EFFECT
      INT_VAR
        opcode_to_delete = 165
    END
END